default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: truyen_api_development

test:
  <<: *default
  database: truyen_api_test

production:
  <<: *default
  database: truyen_api_production
  username: truyen_api
  password: <%= ENV['TRUYEN_API_DATABASE_PASSWORD'] %>
